import type { OpportunityView } from "./types";

/** Static preview data for the marketing page (the marketplace itself reads from Postgres). */
export const PREVIEW_OPPORTUNITIES: OpportunityView[] = [
  {
    id: "opp-financial-analysis",
    title: "Financial Analysis Intern",
    company: "Northwind Capital",
    industry: "Finance",
    description: "Build a three-statement model and quarterly variance pack for a mid-market portfolio company. You’ll present findings to the deal team in week three.",
    skills: ["Financial Modelling", "Excel", "Valuation"],
    duration: "4 weeks",
    durationWeeks: 4,
    paid: true,
    remote: true,
    budget: 24000,
    headcount: 2,
    from: "2026-10-12",
    to: "2026-11-08",
  },
  {
    id: "opp-market-research",
    title: "Market Research Project",
    company: "Aster Labs",
    industry: "Consumer",
    description: "Size the D2C wellness market in tier-2 cities and synthesise 30 customer interviews.",
    skills: ["Market Research", "Power BI", "Survey Design"],
    duration: "3 weeks",
    durationWeeks: 3,
    paid: true,
    remote: true,
    budget: 18000,
    headcount: 3,
    from: "2026-10-14",
    to: "2026-11-02",
  },
  {
    id: "opp-sales-dashboard",
    title: "Sales Dashboard Build",
    company: "Kestrel Logistics",
    industry: "Operations",
    description: "Replace a weekly spreadsheet ritual with a live Power BI dashboard for regional sales heads.",
    skills: ["Power BI", "SQL", "Data Storytelling"],
    duration: "2 weeks",
    durationWeeks: 2,
    paid: false,
    remote: false,
    budget: null,
    headcount: 1,
    from: "2026-10-20",
    to: "2026-11-01",
  },
];
